version: "3.5"

services:
  nginxgw:
    image: nginxgw:v_1.0.0
    ports:
      - 5000:5000 
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 20s
        failure_action: rollback
    restart: always
    volumes:
      - /home/strong1133/docker/strong_nginx/conf:/etc/nginx
      - /home/strong1133/docker/strong_nginx:/var/www
    restart: always
    networks:
      - strong-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  strong-net:
    driver: overlay
